### ISSUE TITLE
Private key exposure vulnerability in Ironclad's DSA signature implementation

### ISSUE THREAD

**Issue by eadmund** [froydnj/ironclad#21]
The experimental IRONCLAD:SIGN-MESSAGE's DSA method uses CL:RANDOM to generate the message secret. Since CL:RANDOM is not cryptographically secure (on SBCL, it's based on the Mersenne Twister, which is highly insecure for crypto applications), it's possible that every message signature to leak a few bits of the private DSA key.

To fix this, some sort of cryptographically-secure random number source should be used--either an OS-specific source, the Fortuna implementation or another.

After it's fixed, all Ironclad users should change their DSA keypairs.

**Comment by eudoxia0** [comment]
This looks like rather a serious problem. Any updates? The code still uses the `random` function.

**Comment by eadmund** [comment]
@froydnj, can you merge d1d9a23 in to fix this?

**Comment by eadmund** [comment]
This was resolved in 60c37e8bdccdaac1c430d1a2982f1df5129e2944.
