### ISSUE TITLE
Possible Bug In SHA512?

### ISSUE THREAD

**Issue by dansommers** [froydnj/ironclad#51]
As part of a larger password hashing algorithm, I repeatedly hash some fixed data and the current output of the hash algorithm.  Some time ago, I wrote the "reference" algorithm in Python, and recently implemented it in Common Lisp, but I had problems verifying some of the existing hashes.  Eventually, I boiled it down to these two programs giving different output:

#! /usr/bin/sbcl --script

(load #P"~/quicklisp/setup.lisp")
(ql:quickload "ironclad")

(defun safe-produce-digest (digester)
  (ironclad:produce-digest
   (ironclad:copy-digest digester)))

(defun do-it (algorithm)
  (format t "==== ~A ====~%" algorithm)
  (let ((digester (ironclad:make-digest algorithm))
	(thing1 (sb-ext:string-to-octets "secret" :external-format :utf-8)))
    (format t "0: ~S~%" (safe-produce-digest digester))
    (loop repeat 10
       for iteration from 1
       do
	 (ironclad:update-digest digester thing1)
	 (ironclad:update-digest digester (safe-produce-digest digester))
	 (format t "~A: ~S~%" iteration (safe-produce-digest digester)))))

(dolist (algorithm '(:md5 :sha512))
  (do-it algorithm))

#! /usr/bin/env python3

import hashlib
import pprint

def pwint(iteration, octets):
    print('{}:'.format(iteration),
          '#(' + ' '.join(str(x) for x in octets) + ')')

def do_it(algorithm):
    print('====', algorithm, '====')
    digester = hashlib.new(algorithm)
    pwint(0, digester.digest())
    for i in range(1, 11):
        digester.update(b'secret')
        digester.update(digester.digest())
        pwint(i, digester.digest())

for algorithm in 'md5', 'sha512':
    do_it(algorithm)

On my system, Debian "testing," debian sbcl 1.2.4.debian, ironclad 0.33 installed with quicklisp, I get this output from the lisp version:

To load "ironclad":
  Load 1 ASDF system:
    ironclad
; Loading "ironclad"
....
==== MD5 ====
0: #(212 29 140 217 143 0 178 4 233 128 9 152 236 248 66 126)
1: #(112 55 100 15 24 255 203 214 6 151 172 226 156 238 237 44)
2: #(186 238 73 57 189 67 246 225 203 112 90 101 70 221 22 86)
3: #(146 224 26 35 232 158 49 154 142 98 194 21 133 235 132 76)
4: #(153 93 209 128 122 194 221 159 59 212 139 179 119 149 30 245)
5: #(43 163 77 99 250 115 214 170 102 123 220 41 73 30 175 239)
6: #(142 129 2 82 61 184 166 175 253 97 48 205 102 107 118 48)
7: #(167 199 30 122 11 83 229 26 95 112 213 66 254 235 65 29)
8: #(164 226 206 198 39 178 37 33 54 180 19 99 72 8 11 161)
9: #(60 174 117 75 50 99 243 122 206 160 212 90 161 230 60 14)
10: #(86 194 131 66 231 114 253 51 24 145 77 143 147 198 118 234)
==== SHA512 ====
0: #(207 131 225 53 126 239 184 189 241 84 40 80 214 109 128 7 214 32 228 5 11
     87 21 220 131 244 169 33 211 108 233 206 71 208 209 60 93 133 242 176 255
     131 24 210 135 126 236 47 99 185 49 189 71 65 122 129 165 56 50 122 249 39
     218 62)
1: #(28 221 93 249 244 234 178 111 170 230 171 211 96 96 241 185 83 255 181 145
     80 26 20 56 38 145 46 74 97 32 1 121 102 5 85 243 18 51 206 240 118 43 27
     175 26 178 65 217 197 145 82 234 180 78 245 195 190 30 243 66 97 117 65
     177)
2: #(91 89 120 217 160 120 225 113 20 96 95 108 5 147 161 234 158 61 76 213 131
     48 39 188 123 169 209 31 12 180 214 128 216 162 247 215 70 97 43 209 184
     74 106 95 213 193 102 251 56 25 228 218 208 236 205 26 102 204 53 94 57
     248 246 103)
3: #(171 19 65 72 1 220 80 162 252 55 22 52 50 34 59 125 75 71 23 156 154 145
     221 64 158 221 231 67 95 55 28 212 201 73 163 122 222 172 132 199 200 244
     15 206 197 225 164 242 214 144 18 76 144 187 148 253 12 110 157 213 160
     250 249 198)
4: #(72 178 139 18 210 125 119 228 21 88 82 19 191 104 216 90 82 217 185 59 106
     10 89 178 26 248 197 198 83 9 51 255 114 69 117 21 232 56 13 63 162 221 14
     170 168 252 41 175 148 34 76 221 243 58 197 76 221 100 150 146 174 204 61
     145)
5: #(205 61 36 120 102 16 163 18 103 45 145 188 117 207 217 117 67 66 228 164
     237 176 106 197 33 191 91 90 74 219 130 134 247 167 110 232 230 13 44 5
     159 5 183 161 109 31 97 11 165 75 45 141 17 147 141 19 11 18 187 45 168
     153 21 2)
6: #(240 187 169 107 91 226 226 238 209 46 21 30 122 52 82 24 124 146 7 65 226
     45 20 178 114 50 103 22 72 202 150 231 157 179 51 158 81 98 78 210 149 84
     190 146 111 2 49 154 102 248 206 168 164 214 65 193 49 69 156 20 82 65 102
     58)
7: #(194 165 208 28 145 94 113 129 229 89 249 99 30 163 24 29 109 171 144 118
     239 137 119 98 195 172 127 142 235 83 241 176 212 24 45 215 249 245 52 116
     101 94 209 20 191 101 135 26 83 189 152 61 234 43 79 34 224 106 203 196
     101 149 201 64)
8: #(223 40 173 243 5 118 66 92 202 255 127 35 228 249 20 166 237 132 169 55 54
     105 202 246 217 228 186 89 240 233 78 152 25 225 110 28 188 227 244 157
     125 147 155 188 184 88 72 158 77 202 51 51 72 20 107 212 25 190 178 31 58
     89 95 246)
9: #(247 97 26 227 126 216 189 75 171 181 89 10 127 97 202 241 18 90 73 255 164
     8 195 188 248 208 212 27 160 216 232 226 61 0 104 119 90 201 112 187 185
     41 30 50 121 143 234 133 134 13 1 132 192 222 46 229 148 224 107 129 224
     197 9 2)
10: #(10 83 125 36 153 157 226 218 97 86 239 103 75 111 212 255 155 99 96 111
      79 232 199 197 249 111 137 67 29 62 151 165 196 225 106 227 120 57 200
      199 61 95 152 92 196 87 240 254 241 157 213 163 179 56 71 164 77 77 169
      142 238 121 216 72)

Using Python 3.4.2 as installed by my OS, I get this output from the Python version:

==== md5 ====
0: #(212 29 140 217 143 0 178 4 233 128 9 152 236 248 66 126)
1: #(112 55 100 15 24 255 203 214 6 151 172 226 156 238 237 44)
2: #(186 238 73 57 189 67 246 225 203 112 90 101 70 221 22 86)
3: #(146 224 26 35 232 158 49 154 142 98 194 21 133 235 132 76)
4: #(153 93 209 128 122 194 221 159 59 212 139 179 119 149 30 245)
5: #(43 163 77 99 250 115 214 170 102 123 220 41 73 30 175 239)
6: #(142 129 2 82 61 184 166 175 253 97 48 205 102 107 118 48)
7: #(167 199 30 122 11 83 229 26 95 112 213 66 254 235 65 29)
8: #(164 226 206 198 39 178 37 33 54 180 19 99 72 8 11 161)
9: #(60 174 117 75 50 99 243 122 206 160 212 90 161 230 60 14)
10: #(86 194 131 66 231 114 253 51 24 145 77 143 147 198 118 234)
==== sha512 ====
0: #(207 131 225 53 126 239 184 189 241 84 40 80 214 109 128 7 214 32 228 5 11 87 21 220 131 244 169 33 211 108 233 206 71 208 209 60 93 133 242 176 255 131 24 210 135 126 236 47 99 185 49 189 71 65 122 129 165 56 50 122 249 39 218 62)
1: #(28 221 93 249 244 234 178 111 170 230 171 211 96 96 241 185 83 255 181 145 80 26 20 56 38 145 46 74 97 32 1 121 102 5 85 243 18 51 206 240 118 43 27 175 26 178 65 217 197 145 82 234 180 78 245 195 190 30 243 66 97 117 65 177)
2: #(91 89 120 217 160 120 225 113 20 96 95 108 5 147 161 234 158 61 76 213 131 48 39 188 123 169 209 31 12 180 214 128 216 162 247 215 70 97 43 209 184 74 106 95 213 193 102 251 56 25 228 218 208 236 205 26 102 204 53 94 57 248 246 103)
3: #(171 19 65 72 1 220 80 162 252 55 22 52 50 34 59 125 75 71 23 156 154 145 221 64 158 221 231 67 95 55 28 212 201 73 163 122 222 172 132 199 200 244 15 206 197 225 164 242 214 144 18 76 144 187 148 253 12 110 157 213 160 250 249 198)
4: #(72 178 139 18 210 125 119 228 21 88 82 19 191 104 216 90 82 217 185 59 106 10 89 178 26 248 197 198 83 9 51 255 114 69 117 21 232 56 13 63 162 221 14 170 168 252 41 175 148 34 76 221 243 58 197 76 221 100 150 146 174 204 61 145)
5: #(205 61 36 120 102 16 163 18 103 45 145 188 117 207 217 117 67 66 228 164 237 176 106 197 33 191 91 90 74 219 130 134 247 167 110 232 230 13 44 5 159 5 183 161 109 31 97 11 165 75 45 141 17 147 141 19 11 18 187 45 168 153 21 2)
6: #(240 187 169 107 91 226 226 238 209 46 21 30 122 52 82 24 124 146 7 65 226 45 20 178 114 50 103 22 72 202 150 231 157 179 51 158 81 98 78 210 149 84 190 146 111 2 49 154 102 248 206 168 164 214 65 193 49 69 156 20 82 65 102 58)
7: #(194 165 208 28 145 94 113 129 229 89 249 99 30 163 24 29 109 171 144 118 239 137 119 98 195 172 127 142 235 83 241 176 212 24 45 215 249 245 52 116 101 94 209 20 191 101 135 26 83 189 152 61 234 43 79 34 224 106 203 196 101 149 201 64)
8: #(121 224 35 111 110 29 23 155 55 144 234 48 0 253 115 143 59 98 23 138 236 30 183 41 24 206 105 113 142 242 156 128 105 91 176 190 140 144 139 239 128 121 229 235 162 34 139 156 53 115 75 209 230 39 239 38 240 14 63 104 24 56 226 107)
9: #(94 171 190 154 21 16 160 49 198 241 71 57 131 193 66 56 194 47 97 91 121 126 225 34 92 210 6 8 77 98 87 187 14 125 55 224 134 138 146 217 100 129 32 49 167 64 81 5 201 20 162 5 239 224 123 184 126 45 186 26 24 120 79 54)
10: #(200 192 97 168 210 16 7 87 251 49 176 93 40 25 231 106 196 150 36 234 95 225 47 93 182 114 72 124 211 137 149 140 188 90 67 206 130 127 72 155 122 202 227 208 192 90 250 67 219 51 86 182 174 98 199 147 168 47 245 249 83 165 84 102)

Note that the md5 output matches all the way through, but the sha512 output diverges between iterations 7 and 8.

As part of producing these examples, I noticed that the diversion occurs at different iterations depending on what I hash.  For instance, if I change "secret" to "password," then the md5 output matches all the way through but the sha512 output diverges between iterations 5 and 6.  The relevent output from that experiment is as follows:

Lisp:
5: #(162 116 241 39 43 97 142 188 82 83 71 182 40 173 237 71 99 250 234 164 155
     255 116 203 203 201 73 91 63 108 77 159 161 33 110 251 28 208 134 166 173
     125 251 83 191 120 46 159 227 152 212 214 104 66 135 7 192 65 1 15 134 248
     14 225)
6: #(71 65 106 206 164 163 145 24 146 26 253 47 32 184 159 145 116 64 237 192
     112 154 184 138 153 186 0 7 248 68 169 10 185 115 221 66 74 247 215 174 3
     147 46 193 210 116 253 2 253 228 35 91 68 186 80 194 102 130 25 230 0 16
     90 44)

Python:
5: #(162 116 241 39 43 97 142 188 82 83 71 182 40 173 237 71 99 250 234 164 155 255 116 203 203 201 73 91 63 108 77 159 161 33 110 251 28 208 134 166 173 125 251 83 191 120 46 159 227 152 212 214 104 66 135 7 192 65 1 15 134 248 14 225)
6: #(157 211 24 1 181 218 212 49 62 44 194 210 59 179 120 12 10 55 253 85 32 228 203 32 251 91 254 235 230 118 13 211 133 49 184 222 243 176 239 94 44 218 164 86 125 145 169 16 193 87 99 20 24 85 205 145 145 219 194 173 51 26 213 227)

Curiously, if I remove *either* hash update in the loop, then both implementations agree for large numbers of iterations.

**Comment by froydnj** [comment]
It looks like a simpler testcase is:

```lisp
(ironclad:digest-sequence :sha512 (make-array 556 :element-type '(unsigned-byte 8) :initial-element 0))
```

```python
print(hashlib.sha512(b'\0' * 556).hexdigest())
```

Lengths of 555 and below seem to work OK.  It's not clear to me yet what tips at 556.

**Comment by froydnj** [comment]
Never mind me.  It's late at night, and I can't be quite sure what's getting typed in.  Nonetheless, there *is* something very strange going on.
