### ISSUE TITLE
Support for DSA with SHA224 and SHA256

### ISSUE THREAD

**Issue by shrdlu68** [froydnj/ironclad#88]
Hello,
Is it possible to include support for DSA with the SHA-2 hashes?

**Comment by glv2** [comment]
The DSA signature function doesn't perform the hashing of the data. You must hash the data and then sign the hash. So you can use any hash function you want.

For example:

``` lisp
(let ((hash (digest-sequence :sha224 data)))
  (sign-message dsa-secret-key hash))
```

**Comment by shrdlu68** [comment]
What about for verification? I get an error a condition about

**Comment by shrdlu68** [comment]
What about for verification? I get an error a condition about

**Comment by shrdlu68** [comment]
What about verification? I get the error " Can only verify exactly 20 bytes of message with DSA".
Do I just truncate? How does it work?

**Comment by glv2** [comment]
I think you are using version 0.33 of the software, where DSA only worked with 20 bytes of data (e.g. a sha1 hash).

In the current version (0.34), DSA can work with any size of data and truncates it if necessary (depending on the number of bits of the *q* parameter of the key).
